# -*- coding: utf-8 -*-
"""CSS_final_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YYYa2wMg3OsP1TVE0WL1AQ8bDboDIsWo

In this notebook, we present our analysis on the feedbacks and respective stakeholder shares on EU Have Your Say Platform.

Lets first get started by loading our data that we scraped from the platform:
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import re

# Load data
df = pd.read_csv('updated_feedback_data_final.csv')

df

import re

#Data cleaning and extractin the main title:
def extract_main_title(text):
    text = str(text)

    text = re.sub(r"(Topic)", r" \1 ", text, flags=re.IGNORECASE)

    # Split at Topic and keep first part
    main = re.split(r"\bTopic\b", text, flags=re.IGNORECASE)[0]

    # Clean whitespace
    main = main.strip()

    return main

df["main_title"] = df["title"].apply(extract_main_title)

"""SOME DESCRIPTIVE STATISTICS ON THE DATA:"""

df_statistics = df.describe()

display(df_statistics.iloc[:, :12])

df["total_citizen"] = df["EU citizen"] + df["Non-EU citizen"]

# Define stakeholder groups
stakeholder_cols = ['EU citizen','Non-EU citizen','total_citizen', 'Company/business', 'Business association',
                    'Non-governmental organisation (NGO)', 'Environmental organisation',
                    'Consumer organisation', 'Trade union']

for col in stakeholder_cols:
    print(f"Share of {col}: {df[col].sum() / df['total_feedback_check'].sum():.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Calculate shares for each stakeholder column
shares_data = []
for col in stakeholder_cols:
    share = df[col].sum() / df['total_feedback_check'].sum()
    shares_data.append({'Stakeholder': col, 'Share': share})

shares_df = pd.DataFrame(shares_data)

# Create the bar plot
plt.figure(figsize=(12, 7))
sns.barplot(x='Share', y='Stakeholder', data=shares_df.sort_values(by='Share', ascending=False), palette='viridis')
plt.title('Share of Feedback by Stakeholder Group')
plt.xlabel('Share of Total Feedback')
plt.ylabel('Stakeholder Group')
plt.tight_layout()

# Save the plot
plt.savefig('stakeholder_shares.png')
plt.show()

print("Stakeholder shares plot saved as 'stakeholder_shares.png'")

df_statistics.to_csv("haveyoursay_stats.csv", index=False)

"""LETS SEE THE TOPIC DISTRIBUTION IN THE DATA:"""

df["topic"].value_counts()

"""PLOT THE TOPIC DISTRIBUTION:"""

import matplotlib.pyplot as plt
import seaborn as sns

topic_counts = df["topic"].value_counts()

plt.figure(figsize=(12, 8))
sns.barplot(x=topic_counts.index, y=topic_counts.values, palette='viridis')
plt.xticks(rotation=90)
plt.title('Distribution of Topics')
plt.xlabel('Topic')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig('topic_distribution.png')
plt.show()

"""MAKE A TABLE FOR TOPIC DISTRIBUTION:"""

topic_counts_df = topic_counts.reset_index()
topic_counts_df.columns = ['Topic', 'Count']
topic_counts_df.to_csv('topic_distribution.csv', index=False)

print("Topic distribution saved as 'topic_distribution.csv'")
display(topic_counts_df.head())

"""LETS RESTRUCTUTE THE TOPICS USING BERT TOPIC MODELING:"""

# BERT MODEL (Use all-mpnet-base-v2)

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans

"""MODEL WITH 10 CLUSTERS (WE FINE TUNED THE NUMBER OF CLUSTERS WITH 10-15 CLUSTER AND RANDOM STATE, THE BEST RESULTS ARE OBTAINED WITH THE FOLLOWING MODEL:)

"""

model = SentenceTransformer('all-mpnet-base-v2')
# model = SentenceTransformer('all-MiniLM-L6-v2')

df["text_for_bert"] = df["topic"] + " " + df["main_title"]

embeddings = model.encode(df["text_for_bert"].tolist())
num_clusters = 10
kmeans = KMeans(n_clusters=num_clusters, random_state=45)
df["semantic_lane"] = kmeans.fit_predict(embeddings)

df["semantic_lane"].value_counts()

"""LOOKS LIKE A BALANCED CLUSTERING AS ABOVE. NOW, LETS SEE WHAT IS INSIDE EVERY CLUSTER:"""

# See what's in each cluster
for i in range(num_clusters):
    print(f"\n--- Cluster {i} Sample Titles ---")
    print(df[df['semantic_lane'] == i]['text_for_bert'].head(5).values)

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Group the text data by semantic_lane
clustered_texts = df.groupby('semantic_lane')['text_for_bert'].apply(lambda x: ' '.join(x))

# Generate and display a word cloud for each cluster
plt.figure(figsize=(20, 25))
for i in range(num_clusters):
    text = clustered_texts.get(i, '') # Get text for the current cluster, default to empty string if no text
    if text:
        wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

        plt.subplot(5, 2, i + 1) # Arrange in a 5x2 grid
        plt.imshow(wordcloud, interpolation='bilinear')
        plt.title(f'Cluster {i} Word Cloud')
        plt.axis('off')

plt.tight_layout()
plt.show()
print("Word clouds for each semantic cluster generated.")

# See what's in each cluster fully
for i in range(num_clusters):
    print(f"\n--- Cluster {i} Sample Titles ---")
    print(df[df['semantic_lane'] == i]['text_for_bert'].values)

"""THIS LOOKS BETTER THAN THE ORIGINAL TOPICS IN THE DATA SINCE THERE ARE NOT CLUSTERS WHICH INCLUDES ONLY A FEW POLICIES, WHICH CAUSED STATISTICAL PORBLEMS FOR THE ANALYSIS WITH THE ORIGINAL CLUSTERS. ALSO, WE SEE THAT SOME OF THE POLCIIES HAS BEEN CLUSTERED TOGETHER EVEN THOUGH THEY DID NOT HAVE THE SAME TOPIC IN THE ORIGINAL DATA WHICH IS A GOOD SIGN THAT THE MODELING WENT BEYOBD INDYSTRIAL CLUSTERS AND GROUPED THEM BY SEMANTIC SENSE ALSO

NOW, LETS DO THE ANALYSIS FOR EACH STAKEHOLDER TYPE:

FIRST, WE DO WALD TEST AND THEN WE FIT A POISSON GLM MODEL WITH HCV3 ON COMMENT LEVEL:
"""

import numpy as np
import pandas as pd
import re
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.multitest import multipletests


# 1) Build our analysis groups

GROUPS = {
    "Citizens (EU+Non-EU)": ["EU citizen", "Non-EU citizen"],
    "Company/business": ["Company/business"],
    "Business associations": ["Business association"],
    "NGOs (platform label)": ["Non-governmental organisation (NGO)"],

    # "Civil society (NGO+Env+Consumer+Union)": [
    #     "Non-governmental organisation (NGO)",
    #     "Environmental organisation",
    #     "Consumer organisation",
    #     "Trade union"
    # ],
}

# Ensure cluster is categorical + drop invalid exposure
df = df[df["total_feedback_check"] > 0].copy()
df["semantic_lane"] = df["semantic_lane"].astype("category")
df["exposure"] = df["total_feedback_check"].astype(float)


# Function for Global Wald test for equality of all cluster rates

def wald_all_equal(pois_no_intercept_fit, categories):
    """
    H0: beta_0 = beta_1 = ... = beta_K  (all log-rates equal)
    For no-intercept model with K+1 cluster coefficients.
    """
    # Get the parameter names in the fitted model
    pnames = list(pois_no_intercept_fit.params.index)

    # We'll build the list in the same order as categories
    expected = [f"C(semantic_lane)[{k}]" for k in categories]

    # Some setups might have different formatting
    if not all(name in pnames for name in expected):
        # some searching:
        parsed = {}
        for nm in pnames:
            m = re.search(r"\[(.+?)\]", nm)
            if m:
                parsed[m.group(1)] = nm
        expected = [parsed[str(k)] for k in categories]

    K = len(expected)
    R = np.zeros((K - 1, K))
    for j in range(1, K):
        R[j - 1, 0] = -1
        R[j - 1, j] = 1

    # Need covariance in same parameter order as expected
    cov = pois_no_intercept_fit.cov_params().loc[expected, expected].values
    return pois_no_intercept_fit.wald_test(R, cov_p=cov)


# Main function for the main analysis per group

def analyze_group(df, group_name, cols, cluster_col="semantic_lane", exposure_col="exposure"):
    d = df.copy()

    # Define group count Y_gi
    d["y_g"] = d[cols].sum(axis=1).astype(float)

    # Policy-level share per policy
    d["share_g"] = d["y_g"] / d[exposure_col]

    # Policy-level mean share per cluster
    policy_level = (
        d.groupby(cluster_col)["share_g"]
        .mean()
        .rename("policy_level_mean")
    )

    #Overall policy level mean rate:
    overall_policy_mean = d["share_g"].mean()


    # Comment-level share per cluster (ratio of sums)
    comment_level = (
        d.groupby(cluster_col)
        .apply(lambda g: g["y_g"].sum() / g[exposure_col].sum())
        .rename("comment_level_pooled")
    )

    # Overall pooled rate
    overall_rate = d["y_g"].sum() / d[exposure_col].sum()
    log_overall = np.log(overall_rate)

    # Poisson no-intercept with exposure, robust SE with HC3
    pois0 = smf.glm(
        "y_g ~ C(semantic_lane) - 1",
        data=d,
        family=sm.families.Poisson(),
        offset=np.log(d[exposure_col])
    ).fit(cov_type="HC3")

    # Extract cluster rates from model: exp(beta_k)
    # which is equal the pooled comment-level rates under Poisson+offset
    model_rates = np.exp(pois0.params)

    # Rename param names to cluster values (0..K-1)
    cats = list(d[cluster_col].cat.categories)
    # Msp param -> cluster
    mapped = {}
    for nm, val in model_rates.items():
        m = re.search(r"\[(.+?)\]", nm)
        if m:
            mapped[m.group(1)] = val

    # model rate series indexed by cluster
    model_rate_series = pd.Series(
        {k: mapped[str(k)] for k in cats},
        name="poisson_rate"
    )

    # Cluster vs overall tests (H0: beta_k = log_overall)
    rows = []
    for k in cats:
        pname = f"C(semantic_lane)[{k}]"
        ttest = pois0.t_test(f"{pname} = {log_overall}")
        rows.append({
            "cluster": k,
            "z": float(ttest.tvalue),
            "p_value": float(ttest.pvalue),
        })
    tests = pd.DataFrame(rows).set_index("cluster").sort_index()

    # Holm correction
    rej, p_adj, _, _ = multipletests(tests["p_value"].values, method="holm")
    tests["p_value_holm"] = p_adj
    tests["significant_5pct_holm"] = rej

    # Representation ratio vs overall pooled
    rep_ratio = (comment_level / overall_rate).rename("representation_ratio")

    # Global Wald test: all cluster rates equal
    wald = wald_all_equal(pois0, cats)

    # Combine into one cluster table
    out = pd.concat([policy_level, comment_level, model_rate_series, rep_ratio, tests], axis=1)
    out.insert(0, "stakeholder_group", group_name)
    out["overall_rate"] = overall_rate
    out["overall_policy_mean"] = overall_policy_mean

    meta = {
        "stakeholder_group": group_name,
        "overall_rate": overall_rate,
        "wald_chi2": float(wald.statistic),
        "wald_df": int(wald.df_denom),
        "wald_p": float(wald.pvalue),
    }

    return out.reset_index().rename(columns={cluster_col: "cluster"}), meta, pois0

# 4) Run for all groups of stakeholders
all_tables = []
meta_rows = []
models = {}

for gname, cols in GROUPS.items():
    tbl, meta, model = analyze_group(df, gname, cols)
    all_tables.append(tbl)
    meta_rows.append(meta)
    models[gname] = model

cluster_results = pd.concat(all_tables, ignore_index=True)
group_summary = pd.DataFrame(meta_rows)

# 5) Formatting

def pct(x):
    return 100 * x

# Add % columns for easy reading
cluster_results["policy_level_mean_pct"] = pct(cluster_results["policy_level_mean"])
cluster_results["overall_policy_mean_pct"] = pct(cluster_results["overall_policy_mean"])
cluster_results["comment_level_pooled_pct"] = pct(cluster_results["comment_level_pooled"])
cluster_results["poisson_rate_pct"] = pct(cluster_results["poisson_rate"])
cluster_results["overall_rate_pct"] = pct(cluster_results["overall_rate"])



# =========================
# 6) Export tables if you want
# =========================
# cluster_results.to_csv("stakeholder_cluster_results.csv", index=False)
# group_summary.to_csv("stakeholder_group_summary.csv", index=False)

# If you want a single wide table per group (clusters as rows) for reporting:
# for g in GROUPS:
#     wide = cluster_results[cluster_results["stakeholder_group"] == g].set_index("cluster")
#     wide.to_csv(f"{g}_cluster_table.csv")

"""LETS SEE THE OVERALL RESULTS:"""

# Sort for readability
cluster_results = cluster_results.rename(columns={"index": "cluster"})
cluster_results = cluster_results.sort_values(["stakeholder_group", "cluster"]).reset_index(drop=True)

print("=== Group-level global heterogeneity tests (Wald) ===")
print(group_summary.sort_values("wald_p"))

print("\n=== Cluster-level table (first rows) ===")
print(cluster_results.head(20))

stakeholders= cluster_results["stakeholder_group"].unique()

for i in stakeholders:
  print(cluster_results[cluster_results["stakeholder_group"] == i][["stakeholder_group", "overall_policy_mean"]].drop_duplicates())

"""Display the tables for each stakeholder group:"""

for i in stakeholders:

  display(cluster_results[cluster_results["stakeholder_group"] == i][["stakeholder_group", "cluster", "policy_level_mean", "overall_policy_mean", "comment_level_pooled", "overall_rate","poisson_rate","representation_ratio", "z", "p_value", "p_value_holm", "significant_5pct_holm" ]])

"""SAVE THE RESULTS TO A CSV:"""

cluster_results.to_csv("stakeholder_cluster_results_long.csv", index=False)
group_summary.to_csv("stakeholder_group_wald_summary.csv", index=False)

print("Saved:",
      "stakeholder_cluster_results_long.csv",
      "stakeholder_group_wald_summary.csv")